#!/bin/sh

# This module requires the following boot parameters:
#     selinux.module - specifies selinux module to be installed.

selinux_finish_hook_handler() {
    if [ "$1" = "pre" ] && [ "$2" = "finish" ]; then
        semodule -r $bootparam_selinux_module
        umount /sys/fs/selinux
    fi
}

selinux_enabled() {
    if [ -z "$bootparam_selinux_module" ]; then
        return 1
    fi

    return 0
}

selinux_run() {
    msg "Loading selinux module: $bootparam_selinux_module"

    mount -t selinuxfs selinuxfs /sys/fs/selinux
    semodule -i $bootparam_selinux_module
}
